# Code Generated by Sidekick is for learning and experimentation purposes only.
from UnleashClient import UnleashClient

_unleash_client = None

def init_unleash():
    global _unleash_client
    if _unleash_client is None:
        _unleash_client = UnleashClient(
            url="http://localhost:4242/api/",
            app_name="dark",
            custom_headers={
                "Authorization": "default:development.03b0f6bd576cb3ff4daa390b0d7d85b11596d15bb64c6e4ed0e85065"
            },
        )
        _unleash_client.initialize_client()
    return _unleash_client

def shutdown_unleash():
    global _unleash_client
    if _unleash_client is not None:
        try:
            _unleash_client.destroy()
        finally:
            _unleash_client = None

def is_enabled(flag_name: str, default: bool = False) -> bool:
    client = init_unleash()
    return client.is_enabled(flag_name,None, default)

